# Datum — Yahoo Finance & Binance Example
Pulls daily OHLCV for **AAPL** (Yahoo) and **BTCUSDT** (Binance) for March 2026.

In [1]:
import sys
import pathlib

# Add src/ to path so datum can be imported without installing the package
sys.path.insert(0, str(pathlib.Path().resolve().parent / "src"))

In [2]:
from datum import Datum

In [3]:
import yfinance as yf

raw_yf = yf.download(
    tickers=["AAPL"],
    start="2026-03-01",
    end="2026-03-31",
    interval="1d",
    auto_adjust=False,
    actions=False,
    group_by="ticker",
    threads=False,
    progress=False,
)

# Flatten to match what Datum produces for easy comparison
raw_yf.columns = raw_yf.columns.droplevel(0)          # drop ticker level
raw_yf = raw_yf[["Open", "High", "Low", "Close", "Volume"]].rename(
    columns=str.lower
)
raw_yf

Price             open        high         low       close    volume
Date
2026-03-02  262.410004  266.529999  260.200012  264.720001  41827900
2026-03-03  263.480011  265.559998  260.130005  263.750000  38568900
2026-03-04  264.649994  266.149994  261.420013  262.519989  39803100
2026-03-05  260.790009  261.559998  257.250000  260.290009  49658600
2026-03-06  258.630005  258.769989  254.369995  257.459991  41120000
2026-03-09  255.690002  261.149994  253.679993  259.880005  38218500
2026-03-10  257.649994  262.480011  256.950012  260.829987  30590800
2026-03-11  261.089996  262.130005  259.549988  260.809998  26218900
2026-03-12  258.660004  258.950012  254.179993  255.759995  40794000
2026-03-13  255.479996  256.329987  249.520004  250.119995  36930000
2026-03-16  252.110001  253.889999  249.880005  252.820007  32074200
2026-03-17  252.960007  255.130005  252.179993  254.229996  32361600
2026-03-18  252.630005  254.940002  249.000000  249.940002  35757900
2026-03-19  249.399994  251.830002  247.300003  248.960007  34864100
2026-03-20  247.979996  249.199997  246.000000  247.990005  88331100
2026-03-23  253.970001  254.600006  250.279999  251.490005  40546100
2026-03-24  250.350006  254.830002  249.550003  251.639999  45152300
2026-03-25  254.100006  255.000000  251.600006  252.619995  28476700
2026-03-26  252.119995  257.000000  250.770004  252.889999  41796700
2026-03-27  253.899994  255.490005  248.070007  248.800003  47900000
2026-03-30  250.070007  250.869995  245.509995  246.630005  39446200

## Yahoo Finance — AAPL

In [4]:
d_equity = Datum(
    tickers=["AAPL"],
    start="2026-03-01",
    end="2026-03-31",
    freq="1d",
    provider="yahoo",
    dropna_policy="forward",
)

prices_equity = d_equity.get_prices()
prices_equity

                                 AAPL                                      \
Price                           close        high         low        open
Date
2026-03-02 00:00:00+00:00  264.720001  266.529999  260.200012  262.410004
2026-03-03 00:00:00+00:00  263.750000  265.559998  260.130005  263.480011
2026-03-04 00:00:00+00:00  262.519989  266.149994  261.420013  264.649994
2026-03-05 00:00:00+00:00  260.290009  261.559998  257.250000  260.790009
2026-03-06 00:00:00+00:00  257.459991  258.769989  254.369995  258.630005
2026-03-09 00:00:00+00:00  259.880005  261.149994  253.679993  255.690002
2026-03-10 00:00:00+00:00  260.829987  262.480011  256.950012  257.649994
2026-03-11 00:00:00+00:00  260.809998  262.130005  259.549988  261.089996
2026-03-12 00:00:00+00:00  255.759995  258.950012  254.179993  258.660004
2026-03-13 00:00:00+00:00  250.119995  256.329987  249.520004  255.479996
2026-03-16 00:00:00+00:00  252.820007  253.889999  249.880005  252.110001
2026-03-17 00:00:00+00:00  254.229996  255.130005  252.179993  252.960007
2026-03-18 00:00:00+00:00  249.940002  254.940002  249.000000  252.630005
2026-03-19 00:00:00+00:00  248.960007  251.830002  247.300003  249.399994
2026-03-20 00:00:00+00:00  247.990005  249.199997  246.000000  247.979996
2026-03-23 00:00:00+00:00  251.490005  254.600006  250.279999  253.970001
2026-03-24 00:00:00+00:00  251.639999  254.830002  249.550003  250.350006
2026-03-25 00:00:00+00:00  252.619995  255.000000  251.600006  254.100006
2026-03-26 00:00:00+00:00  252.889999  257.000000  250.770004  252.119995
2026-03-27 00:00:00+00:00  248.800003  255.490005  248.070007  253.899994
2026-03-30 00:00:00+00:00  246.630005  250.869995  245.509995  250.070007


Price                        volume
Date
2026-03-02 00:00:00+00:00  41827900
2026-03-03 00:00:00+00:00  38568900
2026-03-04 00:00:00+00:00  39803100
2026-03-05 00:00:00+00:00  49658600
2026-03-06 00:00:00+00:00  41120000
2026-03-09 00:00:00+00:00  38218500
2026-03-10 00:00:00+00:00  30590800
2026-03-11 00:00:00+00:00  26218900
2026-03-12 00:00:00+00:00  40794000
2026-03-13 00:00:00+00:00  36930000
2026-03-16 00:00:00+00:00  32074200
2026-03-17 00:00:00+00:00  32361600
2026-03-18 00:00:00+00:00  35757900
2026-03-19 00:00:00+00:00  34864100
2026-03-20 00:00:00+00:00  88331100
2026-03-23 00:00:00+00:00  40546100
2026-03-24 00:00:00+00:00  45152300
2026-03-25 00:00:00+00:00  28476700
2026-03-26 00:00:00+00:00  41796700
2026-03-27 00:00:00+00:00  47900000
2026-03-30 00:00:00+00:00  39446200

In [5]:
d_equity.get_metadata()

{'coverage': {'AAPL': {'start': '2026-03-02 00:00:00+00:00',
   'end': '2026-03-30 00:00:00+00:00'}},
 'missing_data_actions': [],
 'source': 'yahoo'}

## Binance — BTCUSDT

In [ ]:
d_crypto = Datum(
    tickers=["BTCUSDT"],
    start="2026-03-01",
    end="2026-03-31",
    freq="1d",
    provider="binance",
    dropna_policy="strict",
)

prices_crypto = d_crypto.get_prices()
prices_crypto

In [ ]:
d_crypto.get_metadata()

## Schema check — both DataFrames have identical field structure

In [ ]:
equity_fields = prices_equity.columns.get_level_values(1).unique().tolist()
crypto_fields = prices_crypto.columns.get_level_values(1).unique().tolist()

assert equity_fields == crypto_fields, f"Schema mismatch: {equity_fields} vs {crypto_fields}"
print("Fields match:", equity_fields)

## Preprocessor — quality reports & cleaning

`Preprocessor` takes a Datum prices frame and produces:
- **coverage** (start/end/gaps), **missing data** counts, **outlier** flags (z-score on log returns), and **structural quality** checks
- a cleaned OHLCV frame where extreme returns are winsorized to ±threshold·σ

In [ ]:
from datum import Preprocessor

pre = Preprocessor(prices_equity, zscore_threshold=4.0)
pre.coverage_report()

In [ ]:
pre.missing_report()

In [ ]:
pre.outlier_report()

In [ ]:
pre.quality_report()

In [ ]:
cleaned = pre.clean()
cleaned